codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 60%
        threshold: 5%
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "cmd/kantra-ai/main.go"  # Main entry point
  - "**/*_test.go"            # Test files
  - "**/testdata/**"          # Test fixtures
  - "examples/**"             # Example code
  - "validation/**"           # Validation results

flag_management:
  default_rules:
    carryforward: true
