# kantra-ai Configuration File Example
# Place this file as .kantra-ai.yaml in your project directory or home directory
# CLI flags will override these settings

# AI Provider Configuration
provider:
  name: claude       # claude, openai, groq, ollama, together, anyscale, perplexity, openrouter, lmstudio
  model: ""          # Optional: claude-sonnet-4-20250514, gpt-4, llama-3.1-70b-versatile, codellama, etc.
  base-url: ""       # Optional: Custom base URL for OpenAI-compatible APIs (auto-set for presets)

# Input/Output Paths
paths:
  analysis: ""  # Path to Konveyor output.yaml (e.g., ./analysis/output.yaml)
  input: ""     # Path to source code directory (e.g., ./src)

# Cost and Effort Limits
limits:
  max-cost: 0.0   # Maximum spending in USD (0 = no limit)
  max-effort: 0   # Only fix violations with effort <= this value (0 = no limit)

# Filtering Options
filters:
  categories: []      # Filter by category, e.g., ["mandatory", "optional"]
  violation-ids: []   # Filter by specific IDs, e.g., ["javax-to-jakarta-001"]

# Git Integration
git:
  commit-strategy: ""  # per-violation, per-incident, or at-end (empty = no commits)
  create-pr: false     # Automatically create GitHub pull requests (requires commit-strategy and GITHUB_TOKEN)
  branch-prefix: ""    # Custom branch name prefix (default: kantra-ai/remediation-TIMESTAMP)
                       # Note: Actual branch names may include violation IDs or indices depending on strategy

# Build/Test Verification
verification:
  enabled: false      # Enable build/test verification after fixes
  type: test          # "build" or "test"
  strategy: at-end    # per-fix, per-violation, or at-end
  command: ""         # Custom verification command (empty = auto-detect)
  fail-fast: true     # Stop on first verification failure

# General Settings
dry-run: false  # Preview changes without applying them

# Example configurations for common scenarios:

# Minimal config - fix all violations with Claude:
# provider:
#   name: claude
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src

# Conservative config - only mandatory violations, with cost limit:
# provider:
#   name: claude
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src
# limits:
#   max-cost: 5.00
# filters:
#   categories: ["mandatory"]

# Full automation - fixes with git commits, PR creation, and testing:
# provider:
#   name: claude
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src
# git:
#   commit-strategy: per-violation  # Creates one commit per violation type
#   create-pr: true                  # Creates one PR per violation (requires GITHUB_TOKEN)
# verification:
#   enabled: true
#   type: test
#   strategy: at-end

# PR creation with custom branch name:
# provider:
#   name: claude
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src
# git:
#   commit-strategy: at-end
#   create-pr: true
#   branch-prefix: feature/konveyor-migration  # Single PR with custom branch name

# Using Groq (fast, affordable inference):
# provider:
#   name: groq
#   model: llama-3.1-70b-versatile
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src

# Using Ollama (local, free, private):
# provider:
#   name: ollama
#   model: codellama  # or llama3, deepseek-coder, etc.
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src

# Using Together AI (open source models):
# provider:
#   name: together
#   model: meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src

# Using OpenRouter (100+ models):
# provider:
#   name: openrouter
#   model: meta-llama/llama-3.1-70b-instruct
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src

# Using custom OpenAI-compatible API:
# provider:
#   name: openai
#   base-url: https://your-api.com/v1
#   model: your-model
# paths:
#   analysis: ./analysis/output.yaml
#   input: ./src
