version: "1.0"
plan_file: .kantra-ai-plan.yaml
started_at: 2025-12-16T18:02:42.515958-05:00
updated_at: 2025-12-16T18:02:42.524612-05:00
execution_summary:
    total_phases: 3
    completed_phases: 3
    pending_phases: 0
    total_cost: 0
phases:
    - phase_id: phase-1
      status: completed
      started_at: 2025-12-16T18:02:42.516031-05:00
      completed_at: 2025-12-16T18:02:42.519672-05:00
      fixes_applied: 0
      cost: 0
    - phase_id: phase-2
      status: completed
      started_at: 2025-12-16T18:02:42.521949-05:00
      completed_at: 2025-12-16T18:02:42.522687-05:00
      fixes_applied: 0
      cost: 0
    - phase_id: phase-3
      status: completed
      started_at: 2025-12-16T18:02:42.524522-05:00
      completed_at: 2025-12-16T18:02:42.524586-05:00
      fixes_applied: 0
      cost: 0
violations:
    patternfly-v5-to-patternfly-v6-component-props-00090:
        status: failed
        incidents:
            file:///Users/tsanders/Workspace/tackle2-ui/client/src/app/layout/SidebarApp/SidebarApp.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522595-05:00
            file:///opt/input/source/client/src/app/layout/SidebarApp/SidebarApp.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522596-05:00
    patternfly-v5-to-patternfly-v6-component-props-00140:
        status: failed
        incidents:
            file:///Users/tsanders/Workspace/tackle2-ui/client/src/app/components/questionnaire-summary/questionnaire-summary.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519464-05:00
            file:///opt/input/source/client/src/app/components/FilterToolbar/FilterToolbar.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519469-05:00
            file:///opt/input/source/client/src/app/components/ToolbarBulkExpander.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.51947-05:00
            file:///opt/input/source/client/src/app/components/ToolbarBulkSelector.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519471-05:00
            file:///opt/input/source/client/src/app/components/insights/tables/all-insights-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519472-05:00
            file:///opt/input/source/client/src/app/components/insights/tables/single-application-insights-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519474-05:00
            file:///opt/input/source/client/src/app/components/questionnaire-summary/questionnaire-summary.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519476-05:00
            file:///opt/input/source/client/src/app/layout/HeaderApp/HeaderApp.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519492-05:00
            file:///opt/input/source/client/src/app/layout/HeaderApp/SsoToolbarItem.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519493-05:00
            file:///opt/input/source/client/src/app/pages/applications/analysis-wizard/custom-rules.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519494-05:00
            file:///opt/input/source/client/src/app/pages/applications/application-detail-drawer/application-facts.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519494-05:00
            file:///opt/input/source/client/src/app/pages/applications/application-detail-drawer/components/application-tags.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519495-05:00
            file:///opt/input/source/client/src/app/pages/applications/application-detail-drawer/tab-tasks-content.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519496-05:00
            file:///opt/input/source/client/src/app/pages/applications/applications-table/applications-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519499-05:00
            file:///opt/input/source/client/src/app/pages/applications/applications-table/components/manage-columns-toolbar.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519512-05:00
            file:///opt/input/source/client/src/app/pages/applications/manage-imports-details/manage-imports-details.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519513-05:00
            file:///opt/input/source/client/src/app/pages/applications/manage-imports/manage-imports.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519516-05:00
            file:///opt/input/source/client/src/app/pages/archetypes/archetypes-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519518-05:00
            file:///opt/input/source/client/src/app/pages/archetypes/target-profiles-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519518-05:00
            file:///opt/input/source/client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519549-05:00
            file:///opt/input/source/client/src/app/pages/asset-generators/asset-generators.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519551-05:00
            file:///opt/input/source/client/src/app/pages/asset-generators/components/generator-collection-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519552-05:00
            file:///opt/input/source/client/src/app/pages/controls/business-services/business-services.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519554-05:00
            file:///opt/input/source/client/src/app/pages/controls/job-functions/job-functions.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519555-05:00
            file:///opt/input/source/client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519557-05:00
            file:///opt/input/source/client/src/app/pages/controls/stakeholders/stakeholders.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519558-05:00
            file:///opt/input/source/client/src/app/pages/controls/tags/tag-categories-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.51956-05:00
            file:///opt/input/source/client/src/app/pages/dependencies/dependencies.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519561-05:00
            file:///opt/input/source/client/src/app/pages/dependencies/dependency-apps-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519577-05:00
            file:///opt/input/source/client/src/app/pages/external/jira/trackers.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519579-05:00
            file:///opt/input/source/client/src/app/pages/identities/identities.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519581-05:00
            file:///opt/input/source/client/src/app/pages/insights/affected-applications-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519582-05:00
            file:///opt/input/source/client/src/app/pages/insights/insight-affected-files-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519582-05:00
            file:///opt/input/source/client/src/app/pages/issues/affected-applications-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519583-05:00
            file:///opt/input/source/client/src/app/pages/issues/issue-affected-files-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519584-05:00
            file:///opt/input/source/client/src/app/pages/migration-targets/migration-targets.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519585-05:00
            file:///opt/input/source/client/src/app/pages/migration-waves/components/manage-applications-form.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519586-05:00
            file:///opt/input/source/client/src/app/pages/migration-waves/components/stakeholders-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519587-05:00
            file:///opt/input/source/client/src/app/pages/migration-waves/components/wave-applications-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519588-05:00
            file:///opt/input/source/client/src/app/pages/migration-waves/components/wave-status-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519589-05:00
            file:///opt/input/source/client/src/app/pages/migration-waves/migration-waves.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519591-05:00
            file:///opt/input/source/client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519592-05:00
            file:///opt/input/source/client/src/app/pages/source-platforms/components/platform-applications-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519594-05:00
            file:///opt/input/source/client/src/app/pages/source-platforms/source-platforms.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519595-05:00
            file:///opt/input/source/client/src/app/pages/tasks/tasks-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519596-05:00
    patternfly-v5-to-patternfly-v6-components-00060:
        status: failed
        incidents:
            file:///opt/input/source/client/src/app/components/BreadCrumbPath.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.521994-05:00
            file:///opt/input/source/client/src/app/components/questionnaire-summary/questionnaire-summary.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522008-05:00
            file:///opt/input/source/client/src/app/pages/assessment/components/assessment-actions/assessment-actions-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522008-05:00
            file:///opt/input/source/client/src/app/pages/assessment/components/view-archetypes/view-archetypes-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522008-05:00
            file:///opt/input/source/client/src/app/pages/insights/affected-applications-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522009-05:00
            file:///opt/input/source/client/src/app/pages/issues/affected-applications-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522009-05:00
    patternfly-v5-to-patternfly-v6-removed-props-00050:
        status: failed
        incidents:
            file:///opt/input/source/client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522086-05:00
            file:///opt/input/source/client/src/app/components/FilterToolbar/SelectFilterControl.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522087-05:00
            file:///opt/input/source/client/src/app/components/SimpleSelectBasic.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522087-05:00
            file:///opt/input/source/client/src/app/components/SimpleSelectCheckbox.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522087-05:00
            file:///opt/input/source/client/src/app/components/simple-document-viewer/AttachmentToggle.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522088-05:00
            file:///opt/input/source/client/src/app/components/simple-document-viewer/LanguageToggle.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522088-05:00
            file:///opt/input/source/client/src/app/components/simple-document-viewer/SimpleDocumentViewer.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522088-05:00
            file:///opt/input/source/client/src/app/components/target-card/target-card.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522088-05:00
            file:///opt/input/source/client/src/app/hooks/selection/useBulkSelection.ts:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522089-05:00
            file:///opt/input/source/client/src/app/hooks/useSelectionState/useSelectionState.ts:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522091-05:00
            file:///opt/input/source/client/src/app/pages/applications/generate-assets-wizard/step-select-target-profile.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522091-05:00
    patternfly-v5-to-patternfly-v6-removed-props-00110:
        status: failed
        incidents:
            file:///opt/input/source/client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.522687-05:00
    patternfly-v5-to-patternfly-v6-removed-props-00140:
        status: failed
        incidents:
            file:///opt/input/source/client/src/app/components/questionnaire-summary/questionnaire-summary.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.524584-05:00
    patternfly-v5-to-patternfly-v6-removed-props-00150:
        status: failed
        incidents:
            file:///opt/input/source/client/src/app/pages/migration-waves/components/wave-status-table.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.52262-05:00
    patternfly-v5-to-patternfly-v6-removed-props-00160:
        status: failed
        incidents:
            file:///opt/input/source/client/src/app/components/Autocomplete/Autocomplete.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.51967-05:00
            file:///opt/input/source/client/src/app/components/Autocomplete/GroupedAutocomplete.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519671-05:00
            file:///opt/input/source/client/src/app/components/FilterToolbar/FilterToolbar.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519671-05:00
            file:///opt/input/source/client/src/app/components/Icons/IconWithLabel.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519671-05:00
            file:///opt/input/source/client/src/app/pages/reports/components/application-landscape/application-landscape.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519672-05:00
    patternfly-v5-to-patternfly-v6-renamed-props-00180:
        status: failed
        incidents:
            file:///opt/input/source/client/src/app/components/AppTableActionButtons.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519644-05:00
            file:///opt/input/source/client/src/app/layout/HeaderApp/HeaderApp.tsx:
                status: failed
                cost: 0
                timestamp: 2025-12-16T18:02:42.519644-05:00
last_failure:
    phase_id: phase-3
    violation_id: patternfly-v5-to-patternfly-v6-removed-props-00140
    incident_uri: file:///opt/input/source/client/src/app/components/questionnaire-summary/questionnaire-summary.tsx
    error: 'failed to read file /Users/tsanders/Workspace/tackle2-ui/opt/input/source/client/src/app/components/questionnaire-summary/questionnaire-summary.tsx: open /Users/tsanders/Workspace/tackle2-ui/opt/input/source/client/src/app/components/questionnaire-summary/questionnaire-summary.tsx: no such file or directory'
