package gitutil

import (
	"fmt"
	"path/filepath"
	"strings"
)

// FormatPRTitleForViolation creates a PR title for a violation
func FormatPRTitleForViolation(violationID, description string) string {
	// Keep title concise with just the violation ID
	// Full description is included in the PR body
	return fmt.Sprintf("fix: Konveyor violation %s", violationID)
}

// FormatPRBodyForViolation creates a PR body for a violation
func FormatPRBodyForViolation(violationID, description, category string, effort int,
	fixes []FixRecord, providerName string) string {

	var sb strings.Builder

	// Summary section
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("This PR remediates the Konveyor violation: **%s**\n\n", violationID))

	// Violation details
	sb.WriteString(fmt.Sprintf("**Violation:** %s\n", violationID))
	sb.WriteString(fmt.Sprintf("**Category:** %s\n", category))
	sb.WriteString(fmt.Sprintf("**Effort:** %d\n", effort))
	sb.WriteString(fmt.Sprintf("**Description:** %s\n\n", description))

	// Changes section
	sb.WriteString("## Changes\n\n")

	// Count unique files
	filesModified := make(map[string][]int) // map[filepath][]lineNumbers
	for _, fix := range fixes {
		filesModified[fix.Result.FilePath] = append(
			filesModified[fix.Result.FilePath],
			fix.Incident.LineNumber,
		)
	}

	sb.WriteString(fmt.Sprintf("Fixed %d incident(s) across %d file(s):\n\n", len(fixes), len(filesModified)))
	for file, lines := range filesModified {
		if len(lines) == 1 {
			sb.WriteString(fmt.Sprintf("- `%s:%d`\n", file, lines[0]))
		} else {
			lineStrs := make([]string, len(lines))
			for i, line := range lines {
				lineStrs[i] = fmt.Sprintf("%d", line)
			}
			sb.WriteString(fmt.Sprintf("- `%s` (lines: %s)\n", file, strings.Join(lineStrs, ", ")))
		}
	}
	sb.WriteString("\n")

	// AI details section
	sb.WriteString("## AI Remediation Details\n\n")
	totalCost := 0.0
	totalTokens := 0
	for _, fix := range fixes {
		totalCost += fix.Result.Cost
		totalTokens += fix.Result.TokensUsed
	}
	sb.WriteString(fmt.Sprintf("- **Provider:** %s\n", providerName))
	sb.WriteString(fmt.Sprintf("- **Total Cost:** $%.4f\n", totalCost))
	sb.WriteString(fmt.Sprintf("- **Total Tokens:** %d\n\n", totalTokens))

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("*This PR was automatically generated by [kantra-ai](https://github.com/tsanders-rh/kantra-ai)*\n")

	return sb.String()
}

// FormatPRTitleForIncident creates a PR title for a single incident
func FormatPRTitleForIncident(violationID, description, filename string) string {
	return fmt.Sprintf("fix: %s in %s", violationID, filename)
}

// FormatPRBodyForIncident creates a PR body for a single incident
func FormatPRBodyForIncident(violationID, description, filePath string, lineNumber int,
	cost float64, tokens int, providerName string) string {

	var sb strings.Builder

	// Summary section
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("This PR fixes a Konveyor violation in `%s`\n\n", filepath.Base(filePath)))

	// Incident details
	sb.WriteString(fmt.Sprintf("**Violation:** %s\n", violationID))
	sb.WriteString(fmt.Sprintf("**Description:** %s\n", description))
	sb.WriteString(fmt.Sprintf("**File:** `%s`\n", filePath))
	sb.WriteString(fmt.Sprintf("**Line:** %d\n\n", lineNumber))

	// AI details section
	sb.WriteString("## AI Remediation Details\n\n")
	sb.WriteString(fmt.Sprintf("- **Provider:** %s\n", providerName))
	sb.WriteString(fmt.Sprintf("- **Cost:** $%.4f\n", cost))
	sb.WriteString(fmt.Sprintf("- **Tokens:** %d\n\n", tokens))

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("*This PR was automatically generated by [kantra-ai](https://github.com/tsanders-rh/kantra-ai)*\n")

	return sb.String()
}

// FormatPRTitleAtEnd creates a PR title for batch remediation
func FormatPRTitleAtEnd(violationCount int) string {
	if violationCount == 1 {
		return "fix: Konveyor violation remediation"
	}
	return fmt.Sprintf("fix: Konveyor batch remediation (%d violations)", violationCount)
}

// FormatPRBodyAtEnd creates a PR body for batch remediation
func FormatPRBodyAtEnd(fixesByViolation map[string][]FixRecord, providerName string) string {
	var sb strings.Builder

	// Count total incidents
	totalIncidents := 0
	for _, fixes := range fixesByViolation {
		totalIncidents += len(fixes)
	}

	// Summary section
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("This PR remediates **%d** Konveyor violation(s) with **%d** total incident(s) fixed.\n\n",
		len(fixesByViolation), totalIncidents))

	// Violations section
	sb.WriteString("## Violations Fixed\n\n")
	totalCost := 0.0
	totalTokens := 0
	allFilesModified := make(map[string]bool)

	for violationID, fixes := range fixesByViolation {
		if len(fixes) == 0 {
			continue
		}

		// Get category from first fix
		category := fixes[0].Violation.Category
		description := fixes[0].Violation.Description

		// Truncate long descriptions for list view
		shortDesc := description
		if len(shortDesc) > 80 {
			shortDesc = shortDesc[:77] + "..."
		}

		sb.WriteString(fmt.Sprintf("### %s\n\n", violationID))
		sb.WriteString(fmt.Sprintf("- **Category:** %s\n", category))
		sb.WriteString(fmt.Sprintf("- **Description:** %s\n", shortDesc))
		sb.WriteString(fmt.Sprintf("- **Incidents Fixed:** %d\n", len(fixes)))

		// List affected files for this violation
		filesForViolation := make(map[string]bool)
		for _, fix := range fixes {
			filesForViolation[fix.Result.FilePath] = true
			totalCost += fix.Result.Cost
			totalTokens += fix.Result.TokensUsed
			allFilesModified[fix.Result.FilePath] = true
		}

		if len(filesForViolation) <= 5 {
			sb.WriteString("- **Files:**\n")
			for file := range filesForViolation {
				sb.WriteString(fmt.Sprintf("  - `%s`\n", file))
			}
		} else {
			sb.WriteString(fmt.Sprintf("- **Files:** %d files modified\n", len(filesForViolation)))
		}
		sb.WriteString("\n")
	}

	// AI details section
	sb.WriteString("## AI Remediation Details\n\n")
	sb.WriteString(fmt.Sprintf("- **Provider:** %s\n", providerName))
	sb.WriteString(fmt.Sprintf("- **Total Files Modified:** %d\n", len(allFilesModified)))
	sb.WriteString(fmt.Sprintf("- **Total Cost:** $%.4f\n", totalCost))
	sb.WriteString(fmt.Sprintf("- **Total Tokens:** %d\n\n", totalTokens))

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("*This PR was automatically generated by [kantra-ai](https://github.com/tsanders-rh/kantra-ai)*\n")

	return sb.String()
}
