// Package executor provides plan execution with state tracking and resume capability.
//
// The executor loads a migration plan generated by the planner package and executes
// it phase-by-phase, tracking progress in a state file. If execution fails, it can
// be resumed from the failure point using the --resume flag.
package executor

import (
	"github.com/tsanders/kantra-ai/pkg/confidence"
	"github.com/tsanders/kantra-ai/pkg/fixer"
	"github.com/tsanders/kantra-ai/pkg/gitutil"
	"github.com/tsanders/kantra-ai/pkg/provider"
	"github.com/tsanders/kantra-ai/pkg/ux"
)

// Config holds configuration for plan execution.
type Config struct {
	PlanPath      string            // Path to plan file (default: .kantra-ai-plan.yaml)
	StatePath     string            // Path to state file (default: .kantra-ai-state.yaml)
	InputPath     string            // Path to source code directory (required)
	Provider      provider.Provider // AI provider for fixes
	PhaseID       string            // Specific phase to execute (empty = all)
	DryRun        bool              // Preview without applying changes
	GitCommit     string            // Git commit strategy (per-violation, per-incident, at-end, "")
	CreatePR            bool              // Create GitHub pull requests
	PRStrategy          string            // PR creation strategy (per-violation, per-incident, per-phase, at-end, "")
	PRCommentThreshold  float64           // Add inline PR comments for fixes with confidence below this threshold (0.0-1.0, 0 = disabled)
	BranchName          string            // Custom branch name prefix
	Progress            ux.ProgressWriter       // Progress reporting
	Resume              bool                    // Resume from last failure
	BatchConfig         fixer.BatchConfig       // Batch processing configuration
	ConfidenceConfig    confidence.Config       // Confidence threshold configuration
	CommitTracker       *gitutil.CommitTracker  // Git commit tracker (nil if disabled)
	VerifiedTracker     *gitutil.VerifiedCommitTracker // Verified commit tracker (nil if disabled)
	PRTracker           *gitutil.PRTracker      // PR tracker (nil if disabled)
}

// Result contains the result of plan execution with detailed metrics.
type Result struct {
	TotalPhases      int     // Total phases in plan
	ExecutedPhases   int     // Phases that were executed
	CompletedPhases  int     // Phases that completed successfully
	FailedPhases     int     // Phases that failed
	TotalFixes       int     // Total fixes attempted
	SuccessfulFixes  int     // Fixes that succeeded
	FailedFixes      int     // Fixes that failed
	SkippedFixes     int     // Fixes skipped (already completed)
	DuplicateFixes   int     // Fixes skipped (duplicates)
	TotalCost        float64 // Total cost incurred
	TotalTokens      int     // Total tokens used
	StatePath        string  // Path to state file
	ConfidenceStats  *confidence.Stats // Confidence filtering statistics (nil if disabled)
}

// PhaseResult contains the result of executing a single phase.
type PhaseResult struct {
	PhaseID         string
	PhaseName       string
	SuccessfulFixes int
	FailedFixes     int
	SkippedFixes    int // Fixes skipped (already completed)
	DuplicateFixes  int // Fixes skipped (duplicates)
	Cost            float64
	Tokens          int
	Error           error
	ConfidenceStats *confidence.Stats // Confidence filtering statistics (nil if disabled)
}
